AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EventCheckLambda

  Sample SAM Template for EventCheckLambda

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  EventCheckLambda:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: EventCheck/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
